/**
 * OpenAI Client Utility
 * 
 * NOTE: All legal documents in this application are generated exclusively using OpenAI GPT-4.
 * This ensures high-quality, structured output and consistent formatting across all templates.
 * 
 * Centralized OpenAI client initialization and helper functions.
 * This application exclusively uses OpenAI GPT-4 for all AI functionality.
 */

import OpenAI from "openai"
import { OPENAI_MODEL, OPENAI_SETTINGS, SYSTEM_INSTRUCTIONS } from "@/config/openai"

// Lazy initialization function for OpenAI client
// This prevents build-time errors when OPENAI_API_KEY is not set
function getOpenAIClient(): OpenAI {
  if (!process.env.OPENAI_API_KEY) {
    throw new Error(
      "OPENAI_API_KEY is missing. Please add it to your .env.local file.\n" +
      "Get your key from: https://platform.openai.com/api-keys"
    )
  }

  return new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
  })
}

// Use a Proxy to lazily initialize OpenAI only when actually used
// This allows the module to be imported during build without errors
let openaiInstance: OpenAI | null = null

export const openai = new Proxy({} as OpenAI, {
  get(target, prop) {
    if (!openaiInstance) {
      openaiInstance = getOpenAIClient()
    }
    const value = (openaiInstance as any)[prop]
    if (typeof value === "function") {
      return value.bind(openaiInstance)
    }
    return value
  },
})

/**
 * Generate text using GPT-4
 * 
 * @param prompt - The user prompt/instructions
 * @param systemMessage - Optional system message (defaults to legal document generator)
 * @param temperature - Optional temperature override (defaults to 0.2)
 * @returns Generated text content
 */
export async function generateWithGPT4(
  prompt: string,
  systemMessage: string = SYSTEM_INSTRUCTIONS,
  temperature: number = OPENAI_SETTINGS.temperature
): Promise<string> {
  try {
    // Log what we're sending to GPT-4 (only in development)
    if (process.env.NODE_ENV === "development") {
      console.log("\n" + "=".repeat(80))
      console.log("📤 SENDING TO GPT-4:")
      console.log("=".repeat(80))
      console.log("\n🔧 SYSTEM MESSAGE (Instructions):")
      console.log("-".repeat(80))
      console.log(systemMessage.substring(0, 500) + (systemMessage.length > 500 ? "..." : ""))
      console.log(`\n📝 USER PROMPT (Length: ${prompt.length} characters):`)
      console.log("-".repeat(80))
      console.log(prompt.substring(0, 1000) + (prompt.length > 1000 ? "\n... [truncated]" : ""))
      console.log("\n⚙️  MODEL:", OPENAI_MODEL)
      console.log("🌡️  TEMPERATURE:", temperature)
      console.log("=".repeat(80) + "\n")
    }

    const completion = await openai.chat.completions.create({
      model: OPENAI_MODEL,
      messages: [
        {
          role: "system",
          content: systemMessage,
        },
        {
          role: "user",
          content: prompt,
        },
      ],
      temperature,
      max_tokens: OPENAI_SETTINGS.max_tokens,
    })

    // Log response info (only in development)
    if (process.env.NODE_ENV === "development") {
      const responseLength = completion.choices[0]?.message?.content?.length || 0
      console.log("\n" + "=".repeat(80))
      console.log("📥 RESPONSE FROM GPT-4:")
      console.log("=".repeat(80))
      console.log(`✅ Generated ${responseLength} characters`)
      console.log(`📊 Tokens used: ${completion.usage?.total_tokens || "N/A"}`)
      console.log("=".repeat(80) + "\n")
    }

    const content = completion.choices[0]?.message?.content

    if (!content) {
      throw new Error("No content generated by GPT-4")
    }

    return content
  } catch (error: any) {
    // Handle model not found errors (404)
    if (error?.status === 404 || error?.message?.includes("does not exist") || error?.message?.includes("not have access")) {
      const modelName = OPENAI_MODEL
      throw new Error(
        `The model "${modelName}" does not exist or you do not have access to it.\n\n` +
        `Possible solutions:\n` +
        `1. Try using "gpt-4o" instead (set OPENAI_MODEL=gpt-4o in your .env.local)\n` +
        `2. Check your OpenAI account has billing enabled at https://platform.openai.com/account/billing\n` +
        `3. Verify your API key has access to GPT-4 models\n` +
        `4. Check available models at https://platform.openai.com/docs/models\n` +
        `5. Common accessible models: gpt-4o, gpt-4o-mini, gpt-4-turbo`
      )
    }

    // Handle quota errors
    if (error?.message?.includes("quota") || error?.status === 429) {
      throw new Error(
        "OpenAI quota exceeded. Please check your billing at https://platform.openai.com/account/billing"
      )
    }

    // Handle authentication errors
    if (error?.status === 401 || error?.status === 403) {
      throw new Error(
        "OpenAI API authentication failed. Please check your OPENAI_API_KEY."
      )
    }

    throw error
  }
}

/**
 * Build a prompt for legal document generation
 * 
 * @param options - Prompt building options
 * @returns Formatted prompt string
 */
export interface BuildPromptOptions {
  template?: string
  fieldValues?: Record<string, string | number>
  instructions?: string
  additionalContext?: string
}

export function buildPrompt(options: BuildPromptOptions): string {
  const { template, fieldValues, instructions, additionalContext } = options

  let prompt = ""

  if (instructions) {
    prompt += `${instructions}\n\n`
  }

  if (template) {
    prompt += template
  }

  if (fieldValues && Object.keys(fieldValues).length > 0) {
    prompt += "\n\nUser-provided values:\n"
    for (const [key, value] of Object.entries(fieldValues)) {
      prompt += `- ${key}: ${value}\n`
    }
  }

  if (additionalContext) {
    prompt += `\n\nAdditional context: ${additionalContext}`
  }

  return prompt.trim()
}

