"use client"

import Link from "next/link"

interface LegalDisclaimerProps {
  variant?: "default" | "compact" | "inline"
  className?: string
}

/**
 * Legal Disclaimer Component
 * 
 * Displays legal disclaimers to protect the service and set user expectations.
 * Should be reviewed by an attorney before production use.
 */
export default function LegalDisclaimer({ variant = "default", className = "" }: LegalDisclaimerProps) {
  if (variant === "inline") {
    return (
      <p className={`text-xs text-text-muted ${className}`}>
        <strong>Legal Notice:</strong> ContractVault is not a law firm and does not provide legal advice. 
        Generated documents are templates and may not be suitable for your specific situation. 
        Consult with a qualified attorney for legal advice.{" "}
        <Link href="/terms" className="underline hover:text-text-main">
          View Terms
        </Link>
      </p>
    )
  }

  if (variant === "compact") {
    return (
      <div className={`bg-yellow-50 border border-yellow-200 rounded-lg p-3 ${className}`}>
        <p className="text-xs text-yellow-800">
          <strong>Legal Notice:</strong> Not a law firm. Not legal advice.{" "}
          <Link href="/terms" className="underline hover:text-yellow-900">
            Terms
          </Link>
        </p>
      </div>
    )
  }

  return (
    <div className={`bg-yellow-50 border border-yellow-200 rounded-lg p-4 ${className}`}>
      <div className="flex items-start gap-3">
        <svg
          className="w-5 h-5 text-yellow-600 flex-shrink-0 mt-0.5"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
          />
        </svg>
        <div className="flex-1">
          <h4 className="text-sm font-semibold text-yellow-800 mb-2">
            Important Legal Notice
          </h4>
          <p className="text-sm text-yellow-800 leading-relaxed mb-2">
            <strong>ContractVault is not a law firm and does not provide legal advice.</strong> The 
            documents generated by this service are templates and may not be suitable for your 
            specific legal situation. Laws vary by jurisdiction and change over time.
          </p>
          <p className="text-sm text-yellow-800 leading-relaxed mb-2">
            <strong>Before using any generated document:</strong>
          </p>
          <ul className="text-sm text-yellow-800 list-disc list-inside mb-2 space-y-1">
            <li>Review the document carefully with all parties</li>
            <li>Consult with a qualified attorney for legal advice</li>
            <li>Ensure the document complies with your jurisdiction&apos;s laws</li>
            <li>Consider your specific circumstances and needs</li>
          </ul>
          <p className="text-sm text-yellow-800 leading-relaxed">
            By using this service, you acknowledge that you understand these limitations and agree 
            to our{" "}
            <Link href="/terms" className="underline hover:text-yellow-900 font-medium">
              Terms of Service
            </Link>{" "}
            and{" "}
            <Link href="/privacy" className="underline hover:text-yellow-900 font-medium">
              Privacy Policy
            </Link>
            .
          </p>
        </div>
      </div>
    </div>
  )
}



