import type { Metadata } from "next"
import Link from "next/link"
import Logo from "@/components/logo"

export const metadata: Metadata = {
  title: "Terms of Service | ContractVault",
  description: "Terms of Service for ContractVault",
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-bg">
      <div className="container mx-auto px-4 md:px-6 max-w-4xl py-12 md:py-16">
        <div className="mb-8">
          <Link href="/" className="inline-block mb-6">
            <Logo size="md" showText={true} />
          </Link>
        </div>

        <div className="bg-white rounded-lg shadow-sm border border-border p-8 md:p-12">
          <h1 className="text-3xl md:text-4xl font-bold text-text-main mb-6">
            Terms of Service
          </h1>
          <p className="text-sm text-text-muted mb-8">
            Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
          </p>

          <div className="prose prose-lg max-w-none space-y-6 text-text-main">
            <section>
              <h2 className="text-2xl font-semibold text-text-main mb-4">1. Acceptance of Terms</h2>
              <p className="leading-relaxed">
                By accessing and using ContractVault ("Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-text-main mb-4">2. Service Description</h2>
              <p className="leading-relaxed">
                ContractVault provides a platform for generating legal documents based on user-provided information. The Service uses automated processes and templates to create documents, but does not provide legal advice, representation, or attorney-client relationships.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-text-main mb-4">3. Not Legal Advice</h2>
              <p className="leading-relaxed">
                <strong className="text-text-main">IMPORTANT:</strong> ContractVault is not a law firm and does not provide legal advice. The documents generated by this Service are templates and may not be suitable for your specific legal needs. You should consult with a qualified attorney before using any document generated by this Service, especially for:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-4">
                <li>Complex legal matters</li>
                <li>High-value transactions</li>
                <li>Matters involving significant legal or financial risk</li>
                <li>Compliance with specific state, federal, or international laws</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-text-main mb-4">4. Document Validity and Enforceability</h2>
              <p className="leading-relaxed">
                <strong className="text-text-main">DISCLAIMER:</strong> ContractVault makes no representations or warranties regarding the legal validity, enforceability, or suitability of any document generated through this Service. The enforceability of documents may vary by jurisdiction and depend on specific circumstances. You are solely responsible for ensuring that any document meets your legal requirements and complies with applicable laws.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-text-main mb-4">5. Electronic Signatures</h2>
              <p className="leading-relaxed">
                ContractVault provides electronic signature functionality for convenience. While electronic signatures are generally legally binding in many jurisdictions, their enforceability may vary by:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-4">
                <li>Jurisdiction and applicable laws</li>
                <li>Type of document being signed</li>
                <li>Specific requirements of the parties involved</li>
              </ul>
              <p className="leading-relaxed mt-4">
                ContractVault does not guarantee the legal enforceability of electronic signatures. You should consult with legal counsel to determine if electronic signatures are appropriate for your specific use case.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-text-main mb-4">6. User Responsibilities</h2>
              <p className="leading-relaxed">
                You are responsible for:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-4">
                <li>Providing accurate and complete information when generating documents</li>
                <li>Reviewing all generated documents before use</li>
                <li>Consulting with legal professionals when appropriate</li>
                <li>Ensuring compliance with applicable laws and regulations</li>
                <li>Maintaining the confidentiality of your account credentials</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-text-main mb-4">7. Limitation of Liability</h2>
              <p className="leading-relaxed">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, CONTRACTVAULT SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM YOUR USE OF THE SERVICE.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-text-main mb-4">8. Intellectual Property</h2>
              <p className="leading-relaxed">
                Documents generated by you using the Service are your property. However, the templates, software, and Service itself are the property of ContractVault and are protected by copyright and other intellectual property laws.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-text-main mb-4">9. Privacy</h2>
              <p className="leading-relaxed">
                Your use of the Service is also governed by our Privacy Policy. Please review our Privacy Policy to understand our practices.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-text-main mb-4">10. Changes to Terms</h2>
              <p className="leading-relaxed">
                ContractVault reserves the right to modify these terms at any time. We will notify users of any material changes. Your continued use of the Service after such modifications constitutes acceptance of the updated terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-text-main mb-4">11. Contact Information</h2>
              <p className="leading-relaxed">
                If you have any questions about these Terms of Service, please contact us through the Service.
              </p>
            </section>
          </div>

          <div className="mt-12 pt-8 border-t border-border">
            <Link
              href="/"
              className="text-accent hover:text-accent-hover transition-colors"
            >
              ← Back to Home
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}

